// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOpZPbsPeWpIp8Wzs1EVGBJzH36zQlgaY',
    appId: '1:461547696321:web:91e6d6bf0d2ede057ca440',
    messagingSenderId: '461547696321',
    projectId: 'arapp1',
    authDomain: 'arapp1.firebaseapp.com',
    storageBucket: 'arapp1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvpi34jZMDlCQfWLI8mzrlPv2utJEaAo',
    appId: '1:461547696321:android:230e4a3c48e5416b7ca440',
    messagingSenderId: '461547696321',
    projectId: 'arapp1',
    storageBucket: 'arapp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiEXbBpCgWrm_Ex0h3jzTcsPYWi9-MDiU',
    appId: '1:461547696321:ios:1e50785dd1b25c427ca440',
    messagingSenderId: '461547696321',
    projectId: 'arapp1',
    storageBucket: 'arapp1.appspot.com',
    iosBundleId: 'com.example.furni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiEXbBpCgWrm_Ex0h3jzTcsPYWi9-MDiU',
    appId: '1:461547696321:ios:df7ae82c0ffa77e67ca440',
    messagingSenderId: '461547696321',
    projectId: 'arapp1',
    storageBucket: 'arapp1.appspot.com',
    iosBundleId: 'com.example.furni.RunnerTests',
  );
}
